version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: smartleads

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - api
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data:
